- hosts: webservers
  tasks:
    - name: cp war file to tomcat
      copy:
        src: target/maven-web-application.war
        dest: /usr/local/tomcat7/webapps/maven-web-application.war
        notify:
        - Restart tomcat
  handlers:
    - name: Restart tomcat
      service:
        name: tomcat
        state: restarted
