apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spring-app
  name: spring-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
      - name: my-spring-app
        image: 332303016470.dkr.ecr.ap-south-1.amazonaws.com/mydockerrepo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
          name: http
          protocol: TCP
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring-app
    k8s-app: spring-app
  name: spring-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8085
  type: NodePort
  selector:
    app: spring-app
